openapi: 3.0.1
info:
  title: Banking System, API
  description: API for managing transactions between accounts
  version: 1.0.0
  contact:
    email: andyakuliah@example.com
servers:
  - url: http://localhost:5102/api/v1

paths:
  /transactions:
    get:
      summary: Retrieve all transactions
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: Indicates the success of the request
                  message:
                    type: string
                    description: A message describing the result of the request
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        source_account_id:
                          type: integer
                          description: The ID of the source account for the transaction
                        destination_account_id:
                          type: integer
                          description: The ID of the destination account for the transaction
                        amount:
                          type: integer
                          description: The amount of the transaction
  /transactions/{id}:
    get:
      summary: Retrieve a transaction by ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the transaction to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: Indicates the success of the request
                  message:
                    type: string
                    description: A message describing the result of the request
                  data:
                    type: object
                    properties:
                      source_account_id:
                        type: integer
                        description: The ID of the source account for the transaction
                      destination_account_id:
                        type: integer
                        description: The ID of the destination account for the transaction
                      amount:
                        type: integer
                        description: The amount of the transaction
        '404':
          description: Transaction not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: Indicates the failure of the request
                  message:
                    type: string
                    description: Error message indicating transaction not found
                  data:
                    type: string
                    description: Null data for a failed request
